print("hello World")
print("Mary's cosmetics")
print('신씨가 소리질렀다. "도둑이야"')
print('어떤 아저씨가 소리질렀다."안녕"')
print("오늘은","일요일")
print('네이버;카카오;안녕')
print("네이버","카카오","안녕")
print("안녕하세요","저는","이희정이에요")
print("월요일","화요일","수요일",sep=",")
print("목요일","금요일","토요일","일요일",sep="  ")
